buildscript {
    repositories {
        mavenCentral()
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        if (project.hasProperty('artifact_url')) {
            maven {
                url = artifact_url
                credentials {
                    username = project.findProperty('artifact_user_name') ?: ""
                    password = project.hasProperty('artifact_password_command') ? artifact_password_command.execute().text.trim() : ""
                }
            }
        }
        maven {
            url = uri("https://plugins.gradle.org/m2/")
        }
    }
}

subprojects {
    ext.describeVersion = { ->
        def stdout = new java.io.ByteArrayOutputStream()
        exec {
            commandLine 'git', 'describe', '--tags'
            standardOutput = stdout
        }
        return stdout.toString().trim()
    }

    repositories {
        mavenCentral()
    }
}
